# Generated by Django 3.0.4 on 2020-03-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='starredcity',
            options={'verbose_name_plural': 'Starred Cities'},
        ),
        migrations.AddField(
            model_name='starredcity',
            name='icon',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='starredcity',
            name='temp',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='starredcity',
            name='state',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
