# Generated by Django 3.0.4 on 2020-03-30 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20200329_1701'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityWeatherData',
        ),
        migrations.DeleteModel(
            name='StarredCity',
        ),
    ]
