# Generated by Django 3.0.4 on 2020-03-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_auto_20200329_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starredcity',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='starredcity',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='starredcity',
            name='is_home',
        ),
        migrations.RemoveField(
            model_name='starredcity',
            name='state',
        ),
        migrations.RemoveField(
            model_name='starredcity',
            name='temp',
        ),
        migrations.AddField(
            model_name='starredcity',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
