# Generated by Django 3.0.4 on 2020-04-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_auto_20200402_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starredcity',
            name='city_id',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
